package mempool

import (
	"fmt"

	"github.com/sat20-labs/satoshinet/blockchain"
	contract "github.com/sat20-labs/satoshinet/contract"
	framework "github.com/sat20-labs/satoshinet/contract/framework"
	"github.com/sat20-labs/satoshinet/wire"
)

// Stateless admission is independent of AcceptNonStd and also runs for
// orphans and cached transactions. No contract state or remote indexer is
// consulted here. Execution-dependent failures remain the runtime's job.
func checkMempoolContractAndAssetEnvelope(tx *wire.MsgTx) error {
	if tx == nil { return txRuleError(wire.RejectInvalid, "missing transaction") }
	for i, output := range tx.TxOut {
		if output == nil { return txRuleError(wire.RejectInvalid, "nil transaction output") }
		for _, asset := range output.Assets {
			if asset.Name == (wire.AssetName{}) {
				return txRuleError(wire.RejectInvalid, fmt.Sprintf("output %d: satoshi (::) must use value, not TxAssets", i))
			}
		}
		carrier, err := contract.RequiredBindingSats(output.Assets)
		if err != nil { return txRuleError(wire.RejectInvalid, err.Error()) }
		if output.Value < carrier {
			return txRuleError(wire.RejectInvalid, fmt.Sprintf("output %d: insufficient carrier sats for bound assets: %d < %d", i, output.Value, carrier))
		}
	}
	kind, found, err := contract.ClassifyTxPayloadType(tx)
	if err != nil { return txRuleError(wire.RejectInvalid, fmt.Sprintf("malformed contract envelope: %v", err)) }
	if !found { return nil }
	if kind == contract.TxTypeResult || kind == contract.TxTypeCoinbaseStateRoot {
		return txRuleError(wire.RejectInvalid, "contract Result/state-root transactions are generated by block execution")
	}
	if kind != contract.TxTypeDeploy && kind != contract.TxTypeInvoke { return nil }
	var payload []byte
	for _, output := range tx.TxOut {
		partKind, part, parseErr := contract.ReadNullDataScript(output.PkScript)
		if parseErr == nil && partKind == kind { payload = append(payload, part...) }
	}
	if kind == contract.TxTypeDeploy {
		deploy, decodeErr := contract.DecodeDeployPayload(payload)
		if decodeErr != nil { return txRuleError(wire.RejectInvalid, fmt.Sprintf("invalid contract deployment: %v", decodeErr)) }
		err = framework.ValidateDeployGasLimit(deploy.GasLimit, framework.GasConfig{})
	} else {
		invoke, decodeErr := contract.DecodeInvokePayload(payload)
		if decodeErr != nil { return txRuleError(wire.RejectInvalid, fmt.Sprintf("invalid contract invocation: %v", decodeErr)) }
		err = framework.ValidateInvokeGasLimit(invoke.GasLimit, framework.GasConfig{})
	}
	if err != nil { return txRuleError(wire.RejectInvalid, fmt.Sprintf("contract gas admission: %v", err)) }
	return nil
}

// BindingSat is asset metadata, not a sender-selected transfer parameter.
// This mempool policy uses the same fetched UTXOs used for signature checks;
// it does not alter historical block validation or on-disk asset formats.
func checkMempoolBindingMetadata(tx *wire.MsgTx, view *blockchain.UtxoViewpoint) error {
	metadata := make(map[wire.AssetName]uint32)
	for _, input := range tx.TxIn {
		entry := view.LookupEntry(input.PreviousOutPoint)
		if entry == nil || entry.IsSpent() {
			return txRuleError(wire.RejectInvalid, "missing asset metadata input")
		}
		for _, asset := range entry.TxAssets() {
			if binding, ok := metadata[asset.Name]; ok && binding != asset.BindingSat {
				return txRuleError(wire.RejectInvalid, fmt.Sprintf("conflicting input BindingSat for asset %s", asset.Name.String()))
			}
			metadata[asset.Name] = asset.BindingSat
		}
	}
	for _, output := range tx.TxOut {
		for _, asset := range output.Assets {
			binding, ok := metadata[asset.Name]
			if !ok { return txRuleError(wire.RejectInvalid, fmt.Sprintf("asset %s has no input metadata", asset.Name.String())) }
			if binding != asset.BindingSat {
				return txRuleError(wire.RejectInvalid, fmt.Sprintf("asset %s BindingSat changed: %d -> %d", asset.Name.String(), binding, asset.BindingSat))
			}
		}
	}
	return nil
}
