[Application Options]


; Use testnet.
; testnet=1

; 使用主网
mainnet=1

addpeer=seed.sat20.org
addpeer=seed.ordx.market

whitelist=127.0.0.1
whitelist=::1
whitelist=192.168.0.0/24
whitelist=fd00::/16

; 本地节点rpc接口用户名和密码
rpcuser=yourname
rpcpass=yourpassword


; 激活挖矿
generate=true

; 上级节点公钥，二选一
; 如果作为挖矿节点，将市场节点作为接入节点
serverpubkey=022ab2945f61304f117f55d469c341d606ceb729de436c80c0e6ad7819cdd53ce7
; 如果作为核心节点，将引导节点作为接入节点（目前未开放）
; serverpubkey=03ab606f4dffd65965b4a9db957361800f8b03ed16acac11d5a4672801554596d0

; 质押了资产的钱包的公钥，请修改
miningpubkey=


; Indexer server
; 请修改为对应的索引器服务
; indexerscheme=http
; indexerhost="127.0.0.1:8009"  
; indexerproxy="btc/mainnet"
; 比如使用ordx市场的索引器，挖矿需要分成
indexerscheme=https
indexerhost=apiprd.ordx.market
indexerproxy="btc/mainnet"

debuglevel=info

