[Application Options]


; Use testnet.
testnet=1

; 使用主网
; mainnet=1

addpeer=seed.sat20.org
addpeer=seed.ordx.market

whitelist=127.0.0.1
whitelist=::1
whitelist=192.168.0.0/24
whitelist=fd00::/16

; 本地节点rpc接口用户名和密码
rpcuser=your_name
rpcpass=your_password


; 激活挖矿
; generate=true

; 服务节点公钥
; serverpubkey=025fb789035bc2f0c74384503401222e53f72eefdebf0886517ff26ac7985f52ad

; 质押了资产的钱包的公钥，请修改
; miningpubkey=


; Indexer server
; 请修改为对应的索引器服务
indexerhost="127.0.0.1:8019"  
indexerproxy="btc/testnet"

debuglevel=info

